package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"api/graph/generated"
	"api/graph/model"
	"context"
	"encoding/json"
	"fmt"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthResponse, error) {
	return r.AuthService.Register(ctx, input)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	return r.AuthService.Login(ctx, input)
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, code string) (*model.User, error) {
	return r.AuthService.VerifyEmail(ctx, code)
}

// ForgotPassword is the resolver for the forgotPassword field.
func (r *mutationResolver) ForgotPassword(ctx context.Context, email string) (bool, error) {
	return r.AuthService.ForgotPassword(ctx, email)
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, token string, password string) (bool, error) {
	return r.AuthService.ResetPassword(ctx, token, password)
}

// UpdateUserAllergies is the resolver for the updateUserAllergies field.
func (r *mutationResolver) UpdateUserAllergies(ctx context.Context, id string, allergies string) (*model.User, error) {
	return r.AuthService.UpdateAllergies(ctx, id, allergies)
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, id string) (bool, error) {
	return r.AuthService.DeleteAccount(ctx, id)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, name *string, email *string) (*model.User, error) {
	return r.AuthService.UpdateUser(ctx, id, name, email)
}

// CreateRestaurant is the resolver for the createRestaurant field.
func (r *mutationResolver) CreateRestaurant(ctx context.Context, input model.CreateRestaurantInput) (*model.Restaurant, error) {
	return r.RestaurantService.Create(ctx, input)
}

// UpdateRestaurant is the resolver for the updateRestaurant field.
func (r *mutationResolver) UpdateRestaurant(ctx context.Context, id string, input model.UpdateRestaurantInput) (*model.Restaurant, error) {
	return r.RestaurantService.Update(ctx, id, input)
}

// DeleteRestaurant is the resolver for the deleteRestaurant field.
func (r *mutationResolver) DeleteRestaurant(ctx context.Context, id string) (bool, error) {
	return r.RestaurantService.Delete(ctx, id)
}

// CreatePayment is the resolver for the createPayment field.
func (r *mutationResolver) CreatePayment(ctx context.Context, input model.CreatePaymentInput) (*model.Payment, error) {
	return r.PaymentService.Create(ctx, input)
}

// RefundPayment is the resolver for the refundPayment field.
func (r *mutationResolver) RefundPayment(ctx context.Context, input model.RefundPaymentInput) (*model.Payment, error) {
	return r.PaymentService.Refund(ctx, input.Payment, input.Amount)
}

// CreateBooking is the resolver for the createBooking field.
func (r *mutationResolver) CreateBooking(ctx context.Context, input model.CreateBookingInput) (*model.Booking, error) {
	return r.BookingService.Create(ctx, input)
}

// UpdateBooking is the resolver for the updateBooking field.
func (r *mutationResolver) UpdateBooking(ctx context.Context, id string, input model.UpdateBookingInput) (*model.Booking, error) {
	return r.BookingService.Update(ctx, id, input)
}

// DeleteBooking is the resolver for the deleteBooking field.
func (r *mutationResolver) DeleteBooking(ctx context.Context, id string) (bool, error) {
	return r.BookingService.Delete(ctx, id)
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	return r.ProductService.Create(ctx, input)
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	return r.ProductService.Update(ctx, id, input)
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	return r.ProductService.Delete(ctx, id)
}

// CreateReview is the resolver for the createReview field.
func (r *mutationResolver) CreateReview(ctx context.Context, input model.CreateReviewInput) (*model.Review, error) {
	return r.ReviewService.Create(ctx, input)
}

// UpdateReview is the resolver for the updateReview field.
func (r *mutationResolver) UpdateReview(ctx context.Context, id string, input model.UpdateReviewInput) (*model.Review, error) {
	return r.ReviewService.Update(ctx, id, input)
}

// DeleteReview is the resolver for the deleteReview field.
func (r *mutationResolver) DeleteReview(ctx context.Context, id string) (bool, error) {
	return r.ReviewService.Delete(ctx, id)
}

// CreateTable is the resolver for the createTable field.
func (r *mutationResolver) CreateTable(ctx context.Context, input model.CreateTableInput) (*model.Table, error) {
	return r.TableService.Create(ctx, input)
}

// UpdateTable is the resolver for the updateTable field.
func (r *mutationResolver) UpdateTable(ctx context.Context, id string, input model.UpdateTableInput) (*model.Table, error) {
	return r.TableService.Update(ctx, id, input)
}

// DeleteTable is the resolver for the deleteTable field.
func (r *mutationResolver) DeleteTable(ctx context.Context, id string) (bool, error) {
	return r.TableService.Delete(ctx, id)
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.Category, error) {
	return r.CategoryService.Create(ctx, input)
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, input model.UpdateCategoryInput) (*model.Category, error) {
	return r.CategoryService.Update(ctx, id, input)
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	return r.CategoryService.Delete(ctx, id)
}

// CreateEmployee is the resolver for the createEmployee field.
func (r *mutationResolver) CreateEmployee(ctx context.Context, input model.CreateEmployeeInput) (*model.Employee, error) {
	return r.EmployeeService.Create(ctx, input)
}

// UpdateEmployee is the resolver for the updateEmployee field.
func (r *mutationResolver) UpdateEmployee(ctx context.Context, input model.UpdateEmployeeInput) (*model.Employee, error) {
	return r.EmployeeService.Update(ctx, input)
}

// RemoveEmployee is the resolver for the removeEmployee field.
func (r *mutationResolver) RemoveEmployee(ctx context.Context, id string) (bool, error) {
	return r.EmployeeService.Delete(ctx, id)
}

// ---------------------------------------------------------
// ORDERS RESOLVERS (Ordenes)
// ---------------------------------------------------------
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput, idempotencyKey string) (*model.Order, error) {
	newOrder, err := r.OrderService.CreateWithIdempotencyKey(ctx, input, idempotencyKey)

	if err != nil {
		return nil, err
	}

	// 2. --- MAGIA DE WEBSOCKETS ---
	// Avisar a todos los que escuchan ese restaurante
	r.mu.Lock()
	observers := r.OrderObservers[input.Restaurant]
	for _, observer := range observers {
		observer <- newOrder // Enviar la orden al canal
	}
	r.mu.Unlock()

	return newOrder, nil
}

// UpdateOrderStatus is the resolver for the updateOrderStatus field.
func (r *mutationResolver) UpdateOrderStatus(ctx context.Context, id string, status string) (*model.Order, error) {
	updatedOrder, err := r.OrderService.UpdateStatus(ctx, id, status)
	if err != nil {
		return nil, err
	}

	// Avisar a los observadores del cambio de estado
	order, err := r.OrderService.FindOne(ctx, id)
	if err == nil {
		r.mu.Lock()
		observers := r.OrderObservers[order.RestaurantID]
		for _, observer := range observers {
			observer <- updatedOrder
		}
		r.mu.Unlock()
	}

	return updatedOrder, nil
}

// UpdateOrderPayment is the resolver for the updateOrderPayment field.
func (r *mutationResolver) UpdateOrderPayment(ctx context.Context, id string, paid bool) (*model.Order, error) {
	return r.OrderService.UpdatePaidStatus(ctx, id, paid)
}

// AddOrderItems is the resolver for the addOrderItems field.
func (r *mutationResolver) AddOrderItems(ctx context.Context, orderID string, items []*model.OrderItemInput) (*model.Order, error) {
	return r.OrderService.AddItems(ctx, orderID, items)
}

// RemoveOrderItem is the resolver for the removeOrderItem field.
func (r *mutationResolver) RemoveOrderItem(ctx context.Context, orderID string, itemID string) (*model.Order, error) {
	return r.OrderService.RemoveItem(ctx, orderID, itemID)
}

// RemoveOrder is the resolver for the removeOrder field.
func (r *mutationResolver) RemoveOrder(ctx context.Context, id string) (bool, error) {
	return r.OrderService.Delete(ctx, id)
}

// ---------------------------------------------------------
// AUTH RESOLVERS (Autenticación)
// ---------------------------------------------------------
func (r *queryResolver) VerifyToken(ctx context.Context, token *string) (*model.UserWithRestaurant, error) {
	if token == nil {
		return nil, nil
	}
	return r.AuthService.VerifyToken(ctx, *token)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return r.AuthService.GetUser(ctx, id)
}

// ---------------------------------------------------------
// RESTAURANTS RESOLVERS (Restaurantes)
// ---------------------------------------------------------
func (r *queryResolver) Restaurants(ctx context.Context, limit *int, offset *int) ([]*model.Restaurant, error) {
	l := 50
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.RestaurantService.FindAllByRestaurant(ctx, l, o)
}

// Restaurant is the resolver for the restaurant field.
func (r *queryResolver) Restaurant(ctx context.Context, id string) (*model.Restaurant, error) {
	return r.RestaurantService.FindOne(ctx, id)
}

// ---------------------------------------------------------
// PAYMENTS RESOLVERS (Pagos)
// ---------------------------------------------------------
func (r *queryResolver) Payment(ctx context.Context, id string) (*model.Payment, error) {
	return r.PaymentService.GetByID(ctx, id)
}

// Payments is the resolver for the payments field.
func (r *queryResolver) Payments(ctx context.Context, limit *int, offset *int) ([]*model.Payment, error) {
	l := 50
	o := 0

	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}

	return r.PaymentService.GetAll(ctx, l, o)
}

// UserPayments is the resolver for the userPayments field.
func (r *queryResolver) UserPayments(ctx context.Context, userID string, limit *int, offset *int) ([]*model.Payment, error) {
	l := 50
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.PaymentService.GetByUserID(ctx, userID, l, o)
}

// ---------------------------------------------------------
// BOOKINGS RESOLVERS (Reservas)
// ---------------------------------------------------------
func (r *queryResolver) Bookings(ctx context.Context, restaurantID string, limit *int, offset *int) ([]*model.Booking, error) {
	l := 50
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.BookingService.FindAllByRestaurant(ctx, restaurantID, l, o)
}

// BookingsUser is the resolver for the bookingsUser field.
func (r *queryResolver) BookingsUser(ctx context.Context, userID string, limit *int, offset *int) ([]*model.Booking, error) {
	l := 50
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.BookingService.FindAllByUser(ctx, userID, l, o)
}

// Booking is the resolver for the booking field.
func (r *queryResolver) Booking(ctx context.Context, id string) (*model.Booking, error) {
	return r.BookingService.FindOne(ctx, id)
}

// ---------------------------------------------------------
// PRODUCTS RESOLVERS (Productos)
// ---------------------------------------------------------
func (r *queryResolver) Products(ctx context.Context, restaurantID string, limit *int, offset *int) ([]*model.Product, error) {
	l := 50
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.ProductService.FindAllByRestaurant(ctx, restaurantID, l, o)
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	return r.ProductService.FindOne(ctx, id)
}

// ---------------------------------------------------------
// Review RESOLVERS (Reseñas)
// ---------------------------------------------------------
func (r *queryResolver) Reviews(ctx context.Context, restaurantID string, limit *int, offset *int) ([]*model.Review, error) {
	l := 50
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.ReviewService.FindAllByRestaurant(ctx, restaurantID, l, o)
}

// Review is the resolver for the review field.
func (r *queryResolver) Review(ctx context.Context, id string) (*model.Review, error) {
	return r.ReviewService.FindOne(ctx, id)
}

// ---------------------------------------------------------
// Tables RESOLVERS (Mesas)
// ---------------------------------------------------------
func (r *queryResolver) Tables(ctx context.Context, restaurantID string) ([]*model.Table, error) {
	return r.TableService.FindAllByRestaurant(ctx, restaurantID)
}

// Table is the resolver for the table field.
func (r *queryResolver) Table(ctx context.Context, id string) (*model.Table, error) {
	return r.TableService.FindOne(ctx, id)
}

// ---------------------------------------------------------
// CATEGORIES RESOLVERS (Categorias)
// ---------------------------------------------------------
func (r *queryResolver) Categories(ctx context.Context, restaurantID string, limit *int, offset *int) ([]*model.Category, error) {
	l := 50
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.CategoryService.FindAllByRestaurant(ctx, restaurantID, l, o)
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*model.Category, error) {
	return r.CategoryService.FindOne(ctx, id)
}

// ---------------------------------------------------------
// EMPLOYEES RESOLVERS (Empleados)
// ---------------------------------------------------------
func (r *queryResolver) EmployeesByRestaurant(ctx context.Context, restaurantID string, limit *int, offset *int) ([]*model.Employee, error) {
	l := 50
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.EmployeeService.FindAllByRestaurant(ctx, restaurantID, l, o)
}

// Employee is the resolver for the employee field.
func (r *queryResolver) Employee(ctx context.Context, id string) (*model.Employee, error) {
	return r.EmployeeService.FindOne(ctx, id)
}

// OrdersByRestaurant is the resolver for the ordersByRestaurant field.
func (r *queryResolver) OrdersByRestaurant(ctx context.Context, restaurantID string, limit *int, offset *int) ([]*model.Order, error) {
	l := 50
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.OrderService.FindAllByRestaurant(ctx, restaurantID, l, o)
}

// OrdersOpen is the resolver for the ordersOpen field.
func (r *queryResolver) OrdersOpen(ctx context.Context, restaurantID string) ([]*model.Order, error) {
	return r.OrderService.FindOpenOrdersByRestaurant(ctx, restaurantID)
}

// OrdersByUser is the resolver for the ordersByUser field.
func (r *queryResolver) OrdersByUser(ctx context.Context, userID string) ([]*model.Order, error) {
	return r.OrderService.FindAllByUser(ctx, userID)
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	return r.OrderService.FindOne(ctx, id)
}

// OrderCreated is the resolver for the orderCreated field.
func (r *subscriptionResolver) OrderCreated(ctx context.Context, restaurantID int) (<-chan *model.Order, error) {
	// 1. Crear un canal para este cliente específico
	// El buffer de 1 evita bloqueos si el cliente es lento
	ch := make(chan *model.Order, 1)

	// 2. Guardar el canal en la lista de observadores de ese restaurante
	r.mu.Lock()
	r.OrderObservers[restaurantID] = append(r.OrderObservers[restaurantID], ch)
	r.mu.Unlock()

	// 3. Manejar la desconexión (Cuando el cocinero cierra la pestaña)
	go func() {
		<-ctx.Done() // Esperar a que el cliente se vaya
		r.mu.Lock()
		observers := r.OrderObservers[restaurantID]
		for i, observer := range observers {
			if observer == ch {
				r.OrderObservers[restaurantID] = append(observers[:i], observers[i+1:]...)
				break
			}
		}
		close(ch)
		r.mu.Unlock()
	}()

	// 4. Devolver el canal a gqlgen para que lo convierta en WebSocket
	return ch, nil
}

// OrderStatusUpdated is the resolver for the orderStatusUpdated field.
func (r *subscriptionResolver) OrderStatusUpdated(ctx context.Context, restaurantID int) (<-chan *model.Order, error) {
	ch := make(chan *model.Order, 1)

	r.mu.Lock()
	r.OrderObservers[restaurantID] = append(r.OrderObservers[restaurantID], ch)
	r.mu.Unlock()

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		observers := r.OrderObservers[restaurantID]
		for i, observer := range observers {
			if observer == ch {
				r.OrderObservers[restaurantID] = append(observers[:i], observers[i+1:]...)
				break
			}
		}
		close(ch)
		r.mu.Unlock()
	}()

	return ch, nil
}

// ===== WAIT TIME RESOLVERS =====

// EstimatedWaitTime is the resolver for the estimatedWaitTime field.
func (r *queryResolver) EstimatedWaitTime(ctx context.Context, restaurantID string) (int, error) {
	// Obtener ID del restaurante como entero
	var rid int
	fmt.Sscanf(restaurantID, "%d", &rid)

	// Obtener cantidad de items de la orden (esto es un parámetro que debería venir en la query)
	// Por ahora, asumimos un promedio de 2 items
	itemCount := 2

	waitTime, err := r.OrderService.WaitCalc.CalculateWaitTime(ctx, rid, itemCount)
	if err != nil {
		return 0, fmt.Errorf("error calculando tiempo de espera: %w", err)
	}

	return waitTime, nil
}

// RestaurantWaitMetrics is the resolver for the restaurantWaitMetrics field.
func (r *queryResolver) RestaurantWaitMetrics(ctx context.Context, restaurantID string) (*model.RestaurantMetrics, error) {
	var rid int
	fmt.Sscanf(restaurantID, "%d", &rid)

	metrics, err := r.OrderService.WaitCalc.GetRestaurantMetrics(ctx, rid)
	if err != nil {
		return nil, fmt.Errorf("error obteniendo métricas: %w", err)
	}

	return &model.RestaurantMetrics{
		RestaurantID:        restaurantID,
		TotalOrders:         metrics.TotalOrders,
		AveragePrepTime:     metrics.AveragePrepTime,
		MedianPrepTime:      metrics.MedianPrepTime,
		PeakHourOrders:      metrics.PeakHourOrders,
		NonPeakHourOrders:   metrics.NonPeakHourOrders,
		MostCommonItemCount: metrics.MostCommonItemCount,
	}, nil
}

// RecentOrderMetrics is the resolver for the recentOrderMetrics field.
func (r *queryResolver) RecentOrderMetrics(ctx context.Context, restaurantID string, limit *int) ([]*model.PreparedOrderMetric, error) {
	var rid int
	fmt.Sscanf(restaurantID, "%d", &rid)

	limVal := 50
	if limit != nil && *limit > 0 {
		limVal = *limit
	}

	metrics, err := r.OrderService.MetricsS.GetRecentMetrics(ctx, rid, limVal)
	if err != nil {
		return nil, fmt.Errorf("error obteniendo métricas recientes: %w", err)
	}

	result := make([]*model.PreparedOrderMetric, len(metrics))
	for i, m := range metrics {
		result[i] = &model.PreparedOrderMetric{
			OrderID:             fmt.Sprintf("%d", m.OrderID),
			RestaurantID:        fmt.Sprintf("%d", m.RestaurantID),
			ItemCount:           m.ItemCount,
			PreparedTimeMinutes: m.PreparedTimeMinutes,
			CreatedAt:           m.CreatedAt,
			CompletedAt:         m.CompletedAt,
			WasPeakHour:         m.WasPeakHour,
		}
	}

	return result, nil
}

// GetRestaurantPaymentMethod is the resolver for the getRestaurantPaymentMethod field.
func (r *queryResolver) GetRestaurantPaymentMethod(ctx context.Context, userID string) (*model.RestaurantPaymentMethod, error) {
	rid, _ := fmt.Sscanf(userID, "%d", new(int))
	return r.RestaurantPaymentService.GetPaymentMethod(ctx, rid)
}

// GetRestaurantPaymentMethodStatus is the resolver for the getRestaurantPaymentMethodStatus field.
func (r *queryResolver) GetRestaurantPaymentMethodStatus(ctx context.Context, userID string) (*model.RestaurantPaymentMethod, error) {
	return r.GetRestaurantPaymentMethod(ctx, userID)
}

// GetCart is the resolver for the getCart field.
func (r *queryResolver) GetCart(ctx context.Context, userID string) ([]*model.CartItem, error) {
	var uid int
	fmt.Sscanf(userID, "%d", &uid)

	data, err := r.CartService.GetCart(ctx, uid)
	if err != nil {
		return nil, err
	}

	var items []*model.CartItem
	if err := json.Unmarshal(data, &items); err != nil {
		return nil, fmt.Errorf("error al decodificar carrito: %w", err)
	}

	return items, nil
}

// GetTermsContent is the resolver for the getTermsContent field.
func (r *queryResolver) GetTermsContent(ctx context.Context, typeArg model.TermsType) (*model.TermsContent, error) {
	return r.TermsService.GetTermsContent(ctx, typeArg)
}

// GetCurrentTermsAcceptance is the resolver for the getCurrentTermsAcceptance field.
func (r *queryResolver) GetCurrentTermsAcceptance(ctx context.Context, typeArg model.TermsType) (*model.TermsAcceptance, error) {
	return r.TermsService.GetCurrentTermsAcceptance(ctx, 0, typeArg)
}

// CheckPendingTermsAcceptance is the resolver for the checkPendingTermsAcceptance field.
func (r *queryResolver) CheckPendingTermsAcceptance(ctx context.Context) ([]model.TermsType, error) {
	return r.TermsService.CheckPendingTermsAcceptance(ctx, 0)
}

// GetCloudinarySignature is the resolver for the getCloudinarySignature field.
func (r *queryResolver) GetCloudinarySignature(ctx context.Context, publicID string, timestamp int) (*model.CloudinarySignature, error) {
	return r.CloudinaryService.GenerateSignature(ctx, publicID, timestamp)
}

// CreateRestaurantPaymentMethod is the resolver for the createRestaurantPaymentMethod field.
func (r *mutationResolver) CreateRestaurantPaymentMethod(ctx context.Context, userID string, input model.CreateRestaurantPaymentMethodInput) (*model.RestaurantPaymentMethod, error) {
	var rid int
	fmt.Sscanf(userID, "%d", &rid)
	return r.RestaurantPaymentService.CreatePaymentMethod(ctx, rid, input)
}

// UpdateRestaurantPaymentMethod is the resolver for the updateRestaurantPaymentMethod field.
func (r *mutationResolver) UpdateRestaurantPaymentMethod(ctx context.Context, userID string, input model.CreateRestaurantPaymentMethodInput) (*model.RestaurantPaymentMethod, error) {
	return r.CreateRestaurantPaymentMethod(ctx, userID, input)
}

// AddToCart is the resolver for the addToCart field.
func (r *mutationResolver) AddToCart(ctx context.Context, userID string, productID int, quantity int, restaurantID int) (*model.CartItem, error) {
	var uid int
	fmt.Sscanf(userID, "%d", &uid)

	err := r.CartService.AddToCart(ctx, uid, productID, quantity, restaurantID)
	if err != nil {
		return nil, err
	}

	return &model.CartItem{
		ID:           "0",
		ProductID:    fmt.Sprintf("%d", productID),
		Quantity:     quantity,
		RestaurantID: fmt.Sprintf("%d", restaurantID),
	}, nil
}

// UpdateCartItem is the resolver for the updateCartItem field.
func (r *mutationResolver) UpdateCartItem(ctx context.Context, userID string, productID int, quantity int) (*model.CartItem, error) {
	var uid int
	fmt.Sscanf(userID, "%d", &uid)

	err := r.CartService.UpdateCartItem(ctx, uid, productID, quantity)
	if err != nil {
		return nil, err
	}

	return &model.CartItem{
		ID:        "0",
		ProductID: fmt.Sprintf("%d", productID),
		Quantity:  quantity,
	}, nil
}

// RemoveFromCart is the resolver for the removeFromCart field.
func (r *mutationResolver) RemoveFromCart(ctx context.Context, userID string, productID int) (bool, error) {
	var uid int
	fmt.Sscanf(userID, "%d", &uid)

	err := r.CartService.RemoveFromCart(ctx, uid, productID)
	if err != nil {
		return false, err
	}
	return true, nil
}

// ClearCart is the resolver for the clearCart field.
func (r *mutationResolver) ClearCart(ctx context.Context, userID string) (bool, error) {
	var uid int
	fmt.Sscanf(userID, "%d", &uid)

	err := r.CartService.ClearCart(ctx, uid)
	if err != nil {
		return false, err
	}
	return true, nil
}

// AcceptTerms is the resolver for the acceptTerms field.
func (r *mutationResolver) AcceptTerms(ctx context.Context, userID string, typeArg model.TermsType) (*model.TermsAcceptance, error) {
	var uid int
	fmt.Sscanf(userID, "%d", &uid)
	return r.TermsService.AcceptTerms(ctx, uid, typeArg)
}

// --- Subscription Resolvers ---

// SubscriptionPlans is the resolver for the subscriptionPlans field.
func (r *queryResolver) SubscriptionPlans(ctx context.Context) ([]*model.SubscriptionPlan, error) {
	return r.SubscriptionService.GetPlans(ctx)
}

// RestaurantSubscription is the resolver for the restaurantSubscription field.
func (r *queryResolver) RestaurantSubscription(ctx context.Context, restaurantID string) (*model.RestaurantSubscription, error) {
	return r.SubscriptionService.GetByRestaurant(ctx, restaurantID)
}

// CreateSubscription is the resolver for the createSubscription field.
func (r *mutationResolver) CreateSubscription(ctx context.Context, input model.CreateSubscriptionInput) (*model.RestaurantSubscription, error) {
	return r.SubscriptionService.Create(ctx, input)
}

// CancelSubscription is the resolver for the cancelSubscription field.
func (r *mutationResolver) CancelSubscription(ctx context.Context, restaurantID string) (*model.RestaurantSubscription, error) {
	return r.SubscriptionService.Cancel(ctx, restaurantID)
}

// AllSubscriptions is the resolver for the allSubscriptions field.
func (r *queryResolver) AllSubscriptions(ctx context.Context) ([]*model.RestaurantSubscription, error) {
	return r.SubscriptionService.GetAll(ctx)
}

// TotalUsers is the resolver for the totalUsers field.
func (r *queryResolver) TotalUsers(ctx context.Context) (int, error) {
	var count int
	err := r.AuthService.DB.QueryRow(ctx, `SELECT COUNT(*) FROM users`).Scan(&count)
	return count, err
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
