// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthResponse struct {
	AccessToken string `json:"accessToken"`
	User        *User  `json:"user"`
	Restaurant  *int   `json:"restaurant,omitempty"`
}

type Booking struct {
	ID           string      `json:"id"`
	RestaurantID int         `json:"restaurantId"`
	Restaurant   *Restaurant `json:"restaurant"`
	UserID       int         `json:"userId"`
	User         *User       `json:"user"`
	TableID      int         `json:"tableId"`
	People       int         `json:"people"`
	Time         time.Time   `json:"time"`
	Status       string      `json:"status"`
}

type Category struct {
	ID           string      `json:"id"`
	RestaurantID int         `json:"restaurantId"`
	Restaurant   *Restaurant `json:"restaurant"`
	Name         string      `json:"name"`
}

type CreateBookingInput struct {
	Restaurant int       `json:"restaurant"`
	User       int       `json:"user"`
	Table      int       `json:"table"`
	People     int       `json:"people"`
	Time       time.Time `json:"time"`
	Status     string    `json:"status"`
}

type CreateCategoryInput struct {
	Restaurant int    `json:"restaurant"`
	Name       string `json:"name"`
}

type CreateEmployeeInput struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	Password     string `json:"password"`
	Role         string `json:"role"`
	RestaurantID int    `json:"restaurantId"`
	Position     string `json:"position"`
}

type CreateOrderInput struct {
	User       int               `json:"user"`
	UserName   string            `json:"user_name"`
	Restaurant int               `json:"restaurant"`
	Status     string            `json:"status"`
	Type       string            `json:"type"`
	Total      float64           `json:"total"`
	Notes      *string           `json:"notes,omitempty"`
	Table      *int              `json:"table,omitempty"`
	Paid       *bool             `json:"paid,omitempty"`
	Items      []*OrderItemInput `json:"items"`
}

type CreatePaymentInput struct {
	UserID          string  `json:"userId"`
	Amount          float64 `json:"amount"`
	Currency        string  `json:"currency"`
	PaymentMethodID string  `json:"paymentMethodId"`
	Description     *string `json:"description,omitempty"`
}

type CreateProductInput struct {
	Restaurant  int     `json:"restaurant"`
	Category    int     `json:"category"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Ingredients *string `json:"ingredients,omitempty"`
	Allergens   *string `json:"allergens,omitempty"`
	Price       float64 `json:"price"`
	Status      bool    `json:"status"`
	Image       *string `json:"image,omitempty"`
}

type CreateRestaurantInput struct {
	Name        string  `json:"name"`
	Address     string  `json:"address"`
	Email       string  `json:"email"`
	Description string  `json:"description"`
	Image       *string `json:"image,omitempty"`
	Phone       string  `json:"phone"`
	Hours       string  `json:"hours"`
}

type CreateReviewInput struct {
	Restaurant int    `json:"restaurant"`
	User       int    `json:"user"`
	Rating     int    `json:"rating"`
	Comment    string `json:"comment"`
}

type CreateTableInput struct {
	Restaurant int    `json:"restaurant"`
	Number     int    `json:"number"`
	Capacity   int    `json:"capacity"`
	Status     string `json:"status"`
}

type Employee struct {
	ID           string      `json:"id"`
	RestaurantID int         `json:"restaurantId"`
	Restaurant   *Restaurant `json:"restaurant"`
	Position     string      `json:"position"`
	HireDate     *time.Time  `json:"hireDate,omitempty"`
	UserID       int         `json:"userId"`
	User         *User       `json:"user"`
}

type LoginInput struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	Restaurant *int   `json:"restaurant,omitempty"`
}

type Mutation struct {
}

type Order struct {
	ID           string       `json:"id"`
	UserID       int          `json:"userId"`
	User         *User        `json:"user"`
	UserName     string       `json:"user_name"`
	RestaurantID int          `json:"restaurantId"`
	Restaurant   *Restaurant  `json:"restaurant"`
	Status       string       `json:"status"`
	Type         string       `json:"type"`
	Total        float64      `json:"total"`
	Notes        *string      `json:"notes,omitempty"`
	TableID      *int         `json:"tableId,omitempty"`
	Date         time.Time    `json:"date"`
	Paid         bool         `json:"paid"`
	OrderDetail  *OrderDetail `json:"orderDetail,omitempty"`
}

type OrderDetail struct {
	ID        string   `json:"id"`
	Order     int      `json:"order"`
	ProductID int      `json:"productId"`
	Product   *Product `json:"product"`
	Quantity  int      `json:"quantity"`
	Subtotal  float64  `json:"subtotal"`
}

type OrderItemInput struct {
	ProductID int     `json:"productId"`
	Quantity  int     `json:"quantity"`
	Subtotal  float64 `json:"subtotal"`
}

type Payment struct {
	ID                    string  `json:"id"`
	UserID                string  `json:"userId"`
	User                  *User   `json:"user"`
	StripePaymentIntentID string  `json:"stripePaymentIntentId"`
	StripePaymentMethodID *string `json:"stripePaymentMethodId,omitempty"`
	Amount                float64 `json:"amount"`
	Currency              string  `json:"currency"`
	Status                string  `json:"status"`
	Description           *string `json:"description,omitempty"`
	CreatedAt             string  `json:"createdAt"`
	UpdatedAt             string  `json:"updatedAt"`
}

type Product struct {
	ID           string      `json:"id"`
	RestaurantID int         `json:"restaurantId"`
	Restaurant   *Restaurant `json:"restaurant"`
	CategoryID   int         `json:"categoryId"`
	Category     *Category   `json:"category"`
	Name         string      `json:"name"`
	Description  *string     `json:"description,omitempty"`
	Ingredients  *string     `json:"ingredients,omitempty"`
	Allergens    *string     `json:"allergens,omitempty"`
	Price        float64     `json:"price"`
	Status       bool        `json:"status"`
	Image        *string     `json:"image,omitempty"`
}

type Query struct {
}

type RefundPaymentInput struct {
	Payment string   `json:"payment"`
	Amount  *float64 `json:"amount,omitempty"`
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type Restaurant struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Address     string  `json:"address"`
	Email       string  `json:"email"`
	Description string  `json:"description"`
	Image       *string `json:"image,omitempty"`
	Phone       string  `json:"phone"`
	Hours       string  `json:"hours"`
}

type Review struct {
	ID           string      `json:"id"`
	RestaurantID int         `json:"restaurantId"`
	Restaurant   *Restaurant `json:"restaurant"`
	UserID       int         `json:"userId"`
	User         *User       `json:"user"`
	Rating       int         `json:"rating"`
	Comment      string      `json:"comment"`
	Date         time.Time   `json:"date"`
}

type Subscription struct {
}

type Table struct {
	ID           string      `json:"id"`
	RestaurantID int         `json:"restaurantId"`
	Restaurant   *Restaurant `json:"restaurant"`
	BookingID    *int        `json:"bookingId,omitempty"`
	Booking      *Booking    `json:"booking,omitempty"`
	Number       int         `json:"number"`
	Capacity     int         `json:"capacity"`
	Status       string      `json:"status"`
}

type UpdateBookingInput struct {
	ID         string     `json:"id"`
	Restaurant *int       `json:"restaurant,omitempty"`
	User       *int       `json:"user,omitempty"`
	Table      *int       `json:"table,omitempty"`
	People     *int       `json:"people,omitempty"`
	Time       *time.Time `json:"time,omitempty"`
	Status     *string    `json:"status,omitempty"`
}

type UpdateCategoryInput struct {
	ID         string  `json:"id"`
	Restaurant *int    `json:"restaurant,omitempty"`
	Name       *string `json:"name,omitempty"`
}

type UpdateEmployeeInput struct {
	ID           string  `json:"id"`
	Name         *string `json:"name,omitempty"`
	Email        *string `json:"email,omitempty"`
	RestaurantID *int    `json:"restaurantId,omitempty"`
	Position     *string `json:"position,omitempty"`
}

type UpdateOrderInput struct {
	ID     string  `json:"id"`
	Estado *string `json:"estado,omitempty"`
}

type UpdateProductInput struct {
	ID          string   `json:"id"`
	Restaurant  *int     `json:"restaurant,omitempty"`
	Category    *int     `json:"category,omitempty"`
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	Ingredients *string  `json:"ingredients,omitempty"`
	Allergens   *string  `json:"allergens,omitempty"`
	Price       *float64 `json:"price,omitempty"`
	Status      *bool    `json:"status,omitempty"`
	Image       *string  `json:"image,omitempty"`
}

type UpdateRestaurantInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Address     *string `json:"address,omitempty"`
	Email       *string `json:"email,omitempty"`
	Description *string `json:"description,omitempty"`
	Image       *string `json:"image,omitempty"`
	Phone       *string `json:"phone,omitempty"`
	Hours       *string `json:"hours,omitempty"`
}

type UpdateReviewInput struct {
	ID         string  `json:"id"`
	Restaurant *int    `json:"restaurant,omitempty"`
	User       *int    `json:"user,omitempty"`
	Rating     *int    `json:"rating,omitempty"`
	Comment    *string `json:"comment,omitempty"`
}

type UpdateTableInput struct {
	ID         string  `json:"id"`
	Restaurant *int    `json:"restaurant,omitempty"`
	Number     *int    `json:"number,omitempty"`
	BookingID  *int    `json:"bookingId,omitempty"`
	Capacity   *int    `json:"capacity,omitempty"`
	Status     *string `json:"status,omitempty"`
}

type User struct {
	ID         string  `json:"id"`
	Name       *string `json:"name,omitempty"`
	Email      *string `json:"email,omitempty"`
	Role       *string `json:"role,omitempty"`
	IsVerified bool    `json:"isVerified"`
}

type UserWithRestaurant struct {
	ID         string  `json:"id"`
	Name       *string `json:"name,omitempty"`
	Email      *string `json:"email,omitempty"`
	Role       *string `json:"role,omitempty"`
	IsVerified bool    `json:"isVerified"`
	Restaurant *int    `json:"restaurant,omitempty"`
}
