// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuthResponse struct {
	AccessToken string `json:"accessToken"`
	User        *User  `json:"user"`
	Restaurant  *int   `json:"restaurant,omitempty"`
}

type Booking struct {
	ID           string      `json:"id"`
	RestaurantID int         `json:"restaurantId"`
	Restaurant   *Restaurant `json:"restaurant"`
	UserID       int         `json:"userId"`
	User         *User       `json:"user"`
	TableID      int         `json:"tableId"`
	People       int         `json:"people"`
	Time         time.Time   `json:"time"`
	Status       string      `json:"status"`
}

type CartItem struct {
	ID           string  `json:"id"`
	ProductID    string  `json:"productId"`
	ProductName  string  `json:"productName"`
	ProductImage *string `json:"productImage,omitempty"`
	Quantity     int     `json:"quantity"`
	Price        float64 `json:"price"`
	RestaurantID string  `json:"restaurantId"`
}

type Category struct {
	ID           string      `json:"id"`
	RestaurantID int         `json:"restaurantId"`
	Restaurant   *Restaurant `json:"restaurant"`
	Name         string      `json:"name"`
}

type CloudinarySignature struct {
	Signature string `json:"signature"`
	Timestamp int    `json:"timestamp"`
	APIKey    string `json:"apiKey"`
	CloudName string `json:"cloudName"`
	PublicID  string `json:"publicId"`
}

type CreateBookingInput struct {
	Restaurant int       `json:"restaurant"`
	User       int       `json:"user"`
	Table      int       `json:"table"`
	People     int       `json:"people"`
	Time       time.Time `json:"time"`
	Status     string    `json:"status"`
}

type CreateCategoryInput struct {
	Restaurant int    `json:"restaurant"`
	Name       string `json:"name"`
}

type CreateEmployeeInput struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	Password     string `json:"password"`
	Role         string `json:"role"`
	RestaurantID int    `json:"restaurantId"`
	Position     string `json:"position"`
}

type CreateOrderInput struct {
	User       int               `json:"user"`
	UserName   string            `json:"user_name"`
	Restaurant int               `json:"restaurant"`
	Status     string            `json:"status"`
	Type       string            `json:"type"`
	Total      float64           `json:"total"`
	Notes      *string           `json:"notes,omitempty"`
	Table      *int              `json:"table,omitempty"`
	Paid       *bool             `json:"paid,omitempty"`
	Items      []*OrderItemInput `json:"items"`
}

type CreatePaymentInput struct {
	UserID          string  `json:"userId"`
	Amount          float64 `json:"amount"`
	Currency        string  `json:"currency"`
	PaymentMethodID string  `json:"paymentMethodId"`
	Description     *string `json:"description,omitempty"`
	OrderID         *int    `json:"orderId,omitempty"`
}

type CreateProductInput struct {
	Restaurant  int     `json:"restaurant"`
	Category    int     `json:"category"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Ingredients *string `json:"ingredients,omitempty"`
	Allergens   *string `json:"allergens,omitempty"`
	Price       float64 `json:"price"`
	Status      bool    `json:"status"`
	Image       *string `json:"image,omitempty"`
}

type CreateRestaurantInput struct {
	Name        string  `json:"name"`
	Address     string  `json:"address"`
	Email       string  `json:"email"`
	Description string  `json:"description"`
	Image       *string `json:"image,omitempty"`
	Phone       string  `json:"phone"`
	Hours       string  `json:"hours"`
}

type CreateRestaurantPaymentMethodInput struct {
	AccountHolderName string  `json:"accountHolderName"`
	RoutingNumber     string  `json:"routingNumber"`
	CountryCode       *string `json:"countryCode,omitempty"`
}

type CreateReviewInput struct {
	Restaurant int    `json:"restaurant"`
	User       int    `json:"user"`
	Rating     int    `json:"rating"`
	Comment    string `json:"comment"`
}

type CreateTableInput struct {
	Restaurant int    `json:"restaurant"`
	Number     int    `json:"number"`
	Capacity   int    `json:"capacity"`
	Status     string `json:"status"`
}

type Employee struct {
	ID           string      `json:"id"`
	RestaurantID int         `json:"restaurantId"`
	Restaurant   *Restaurant `json:"restaurant"`
	Position     string      `json:"position"`
	HireDate     *time.Time  `json:"hireDate,omitempty"`
	UserID       int         `json:"userId"`
	User         *User       `json:"user"`
}

type LoginInput struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	Restaurant *int   `json:"restaurant,omitempty"`
}

type Mutation struct {
}

type Order struct {
	ID                string       `json:"id"`
	UserID            int          `json:"userId"`
	User              *User        `json:"user"`
	UserName          string       `json:"user_name"`
	RestaurantID      int          `json:"restaurantId"`
	Restaurant        *Restaurant  `json:"restaurant"`
	Status            string       `json:"status"`
	Type              string       `json:"type"`
	Total             float64      `json:"total"`
	Notes             *string      `json:"notes,omitempty"`
	TableID           *int         `json:"tableId,omitempty"`
	Date              time.Time    `json:"date"`
	Paid              bool         `json:"paid"`
	OrderDetail       *OrderDetail `json:"orderDetail,omitempty"`
	EstimatedWaitTime int          `json:"estimatedWaitTime"`
	ActualWaitTime    *int         `json:"actualWaitTime,omitempty"`
	CompletedAt       *time.Time   `json:"completedAt,omitempty"`
}

type OrderDetail struct {
	ID        string   `json:"id"`
	Order     int      `json:"order"`
	ProductID int      `json:"productId"`
	Product   *Product `json:"product"`
	Quantity  int      `json:"quantity"`
	Subtotal  float64  `json:"subtotal"`
}

type OrderItemInput struct {
	ProductID int     `json:"productId"`
	Quantity  int     `json:"quantity"`
	Subtotal  float64 `json:"subtotal"`
}

type Payment struct {
	ID                         string   `json:"id"`
	UserID                     string   `json:"userId"`
	User                       *User    `json:"user"`
	StripePaymentIntentID      string   `json:"stripePaymentIntentId"`
	StripePaymentMethodID      *string  `json:"stripePaymentMethodId,omitempty"`
	Amount                     float64  `json:"amount"`
	Currency                   string   `json:"currency"`
	Status                     string   `json:"status"`
	Description                *string  `json:"description,omitempty"`
	StripeApplicationFeeAmount *float64 `json:"stripeApplicationFeeAmount,omitempty"`
	PaymentMethodType          *string  `json:"paymentMethodType,omitempty"`
	CreatedAt                  string   `json:"createdAt"`
	UpdatedAt                  string   `json:"updatedAt"`
	OrderID                    *int     `json:"orderId,omitempty"`
}

type PreparedOrderMetric struct {
	OrderID             string    `json:"orderId"`
	RestaurantID        string    `json:"restaurantId"`
	ItemCount           int       `json:"itemCount"`
	PreparedTimeMinutes int       `json:"preparedTimeMinutes"`
	CreatedAt           time.Time `json:"createdAt"`
	CompletedAt         time.Time `json:"completedAt"`
	WasPeakHour         bool      `json:"wasPeakHour"`
}

type Product struct {
	ID           string      `json:"id"`
	RestaurantID int         `json:"restaurantId"`
	Restaurant   *Restaurant `json:"restaurant"`
	CategoryID   int         `json:"categoryId"`
	Category     *Category   `json:"category"`
	Name         string      `json:"name"`
	Description  *string     `json:"description,omitempty"`
	Ingredients  *string     `json:"ingredients,omitempty"`
	Allergens    *string     `json:"allergens,omitempty"`
	Price        float64     `json:"price"`
	Status       bool        `json:"status"`
	Image        *string     `json:"image,omitempty"`
}

type Query struct {
}

type RefundPaymentInput struct {
	Payment string   `json:"payment"`
	Amount  *float64 `json:"amount,omitempty"`
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type Restaurant struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Address     string  `json:"address"`
	Email       string  `json:"email"`
	Description string  `json:"description"`
	Image       *string `json:"image,omitempty"`
	Phone       string  `json:"phone"`
	Hours       string  `json:"hours"`
}

type RestaurantMetrics struct {
	RestaurantID        string `json:"restaurantId"`
	TotalOrders         int    `json:"totalOrders"`
	AveragePrepTime     int    `json:"averagePrepTime"`
	MedianPrepTime      int    `json:"medianPrepTime"`
	PeakHourOrders      int    `json:"peakHourOrders"`
	NonPeakHourOrders   int    `json:"nonPeakHourOrders"`
	MostCommonItemCount int    `json:"mostCommonItemCount"`
}

type RestaurantPaymentMethod struct {
	ID                        string     `json:"id"`
	RestaurantID              string     `json:"restaurantId"`
	StripeConnectAccountID    *string    `json:"stripeConnectAccountId,omitempty"`
	StripeOnboardingURL       *string    `json:"stripeOnboardingUrl,omitempty"`
	StripeOnboardingCompleted bool       `json:"stripeOnboardingCompleted"`
	AccountHolderName         string     `json:"accountHolderName"`
	AccountType               string     `json:"accountType"`
	BankAccountLast4          *string    `json:"bankAccountLast4,omitempty"`
	RoutingNumber             *string    `json:"routingNumber,omitempty"`
	CountryCode               string     `json:"countryCode"`
	Status                    string     `json:"status"`
	VerificationRequiredAt    *time.Time `json:"verificationRequiredAt,omitempty"`
	ActivatedAt               *time.Time `json:"activatedAt,omitempty"`
	CreatedAt                 time.Time  `json:"createdAt"`
	UpdatedAt                 time.Time  `json:"updatedAt"`
}

type Review struct {
	ID           string      `json:"id"`
	RestaurantID int         `json:"restaurantId"`
	Restaurant   *Restaurant `json:"restaurant"`
	UserID       int         `json:"userId"`
	User         *User       `json:"user"`
	Rating       int         `json:"rating"`
	Comment      string      `json:"comment"`
	Date         time.Time   `json:"date"`
}

type Subscription struct {
}

type Table struct {
	ID           string      `json:"id"`
	RestaurantID int         `json:"restaurantId"`
	Restaurant   *Restaurant `json:"restaurant"`
	BookingID    *int        `json:"bookingId,omitempty"`
	Booking      *Booking    `json:"booking,omitempty"`
	Number       int         `json:"number"`
	Capacity     int         `json:"capacity"`
	Status       string      `json:"status"`
}

type TermsAcceptance struct {
	ID         string    `json:"id"`
	TermsType  TermsType `json:"termsType"`
	AcceptedAt time.Time `json:"acceptedAt"`
}

type TermsContent struct {
	Type        TermsType `json:"type"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	Version     string    `json:"version"`
	LastUpdated time.Time `json:"lastUpdated"`
}

type UpdateBookingInput struct {
	ID         string     `json:"id"`
	Restaurant *int       `json:"restaurant,omitempty"`
	User       *int       `json:"user,omitempty"`
	Table      *int       `json:"table,omitempty"`
	People     *int       `json:"people,omitempty"`
	Time       *time.Time `json:"time,omitempty"`
	Status     *string    `json:"status,omitempty"`
}

type UpdateCategoryInput struct {
	ID         string  `json:"id"`
	Restaurant *int    `json:"restaurant,omitempty"`
	Name       *string `json:"name,omitempty"`
}

type UpdateEmployeeInput struct {
	ID           string  `json:"id"`
	Name         *string `json:"name,omitempty"`
	Email        *string `json:"email,omitempty"`
	RestaurantID *int    `json:"restaurantId,omitempty"`
	Position     *string `json:"position,omitempty"`
}

type UpdateOrderInput struct {
	ID     string  `json:"id"`
	Estado *string `json:"estado,omitempty"`
}

type UpdateProductInput struct {
	ID          string   `json:"id"`
	Restaurant  *int     `json:"restaurant,omitempty"`
	Category    *int     `json:"category,omitempty"`
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	Ingredients *string  `json:"ingredients,omitempty"`
	Allergens   *string  `json:"allergens,omitempty"`
	Price       *float64 `json:"price,omitempty"`
	Status      *bool    `json:"status,omitempty"`
	Image       *string  `json:"image,omitempty"`
}

type UpdateRestaurantInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Address     *string `json:"address,omitempty"`
	Email       *string `json:"email,omitempty"`
	Description *string `json:"description,omitempty"`
	Image       *string `json:"image,omitempty"`
	Phone       *string `json:"phone,omitempty"`
	Hours       *string `json:"hours,omitempty"`
}

type UpdateReviewInput struct {
	ID         string  `json:"id"`
	Restaurant *int    `json:"restaurant,omitempty"`
	User       *int    `json:"user,omitempty"`
	Rating     *int    `json:"rating,omitempty"`
	Comment    *string `json:"comment,omitempty"`
}

type UpdateTableInput struct {
	ID         string  `json:"id"`
	Restaurant *int    `json:"restaurant,omitempty"`
	Number     *int    `json:"number,omitempty"`
	BookingID  *int    `json:"bookingId,omitempty"`
	Capacity   *int    `json:"capacity,omitempty"`
	Status     *string `json:"status,omitempty"`
}

type User struct {
	ID         string  `json:"id"`
	Name       *string `json:"name,omitempty"`
	Email      *string `json:"email,omitempty"`
	Role       *string `json:"role,omitempty"`
	IsVerified bool    `json:"isVerified"`
	Allergies  *string `json:"allergies,omitempty"`
}

type UserWithRestaurant struct {
	ID         string  `json:"id"`
	Name       *string `json:"name,omitempty"`
	Email      *string `json:"email,omitempty"`
	Role       *string `json:"role,omitempty"`
	IsVerified bool    `json:"isVerified"`
	Restaurant *int    `json:"restaurant,omitempty"`
}

type TermsType string

const (
	TermsTypeUserTerms       TermsType = "USER_TERMS"
	TermsTypeRestaurantTerms TermsType = "RESTAURANT_TERMS"
	TermsTypePrivacyPolicy   TermsType = "PRIVACY_POLICY"
)

var AllTermsType = []TermsType{
	TermsTypeUserTerms,
	TermsTypeRestaurantTerms,
	TermsTypePrivacyPolicy,
}

func (e TermsType) IsValid() bool {
	switch e {
	case TermsTypeUserTerms, TermsTypeRestaurantTerms, TermsTypePrivacyPolicy:
		return true
	}
	return false
}

func (e TermsType) String() string {
	return string(e)
}

func (e *TermsType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TermsType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TermsType", str)
	}
	return nil
}

func (e TermsType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TermsType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TermsType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
