events {
    worker_connections 1024;
}

http {
    # Definimos nuestro backend (el nombre "app" viene del docker-compose)
    upstream go_backend {
        server app:8080;
    }

    server {
        listen 80;

        location / {
            # Redirigir todo el tráfico al backend de Go
            proxy_pass http://go_backend;
            
            # Headers importantes para que Go sepa quién es el cliente real
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}